# Generated by Django 3.0.7 on 2020-06-21 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='lasttname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
