# Generated by Django 3.0.7 on 2020-06-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200621_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
