# Generated by Django 3.0.7 on 2020-06-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200621_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_photo_5',
        ),
    ]
